

import Link from "next/link";
import { FaChevronRight } from "react-icons/fa6";
import { RxBorderStyle } from "react-icons/rx";
import { FaMapMarkerAlt, FaPhoneAlt, FaEnvelope,  } from 'react-icons/fa';
import { GoProjectSymlink } from "react-icons/go";
import { GiFactory } from "react-icons/gi";
import { HiOutlineMail } from "react-icons/hi";
import { IoCellular } from "react-icons/io5";
import { TbBuildingFactory2 } from "react-icons/tb";
export async function generateMetadata() {
    return {
      title: 'Samir Textile',
      description: "Generated by create Contact Page",
    }
  }

const ContactPage=()=>{
    return(
<div>
<div className="w-full bg-cover bg-center mb-5" style={{backgroundImage: 'url("/img/StockCake-Textile Factory Scene_1728011217.jpg")'}}>
  <div className="bg-black/70  py-10 sm:py-20">
    <div className="container mx-auto text-center">
      {/* Heading */}
      <h1 className=" text-4xl sm:text-6xl font-semibold text-white mb-3 animate-slide-in-down">
       Contact  Us
      </h1>
      {/* Breadcrumb Navigation */}
      <nav aria-label="breadcrumb">
        <ol className="flex justify-center items-center space-x-3 text-sm uppercase text-white pt-2">
          <li>
            <Link href={"/"} className="text-[#F56800] text-lg">Home </Link>
          </li>
          <li><FaChevronRight /></li>
          <li className="text-white text-lg"> Contact us</li>
        </ol>
      </nav>
    </div>
  </div>
</div>
<div className="px-4 sm:px-20 py-10">
<div className="text-center pb-6" style={{ maxWidth: "500px", margin: "0 auto" }}>
      {/* <p className="text-[#F56800] flex justify-center text-lg font-semibold uppercase  inline-block py-1 rounded pt-3 sm:pt-0 sm:mb-2 flex items-center">
  
   Contact Us

</p> */}

        
      </div>
  
  <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mt-8">
    {/* Contact Info Boxes */}
    

    {/* Google Map */}
    <div>
    <div className="flex border-b pb-3 mb-3">
        <div className="flex-shrink-0  rounded-full p-4">
          <FaMapMarkerAlt className="text-[#F56800]" />
        </div>
        <div className="ml-3">
          <h6 className="font-bold text-[#000]">Head Office</h6>
          <span className="text-[#596277]">Wakil Tower (10 th Floor) Ta-131, Gulshan Badda Link Road, Dhaka-1212, Bangladesh</span>
        </div>
      </div>
      <div className="flex border-b pb-3 mb-3">
        <div className="flex-shrink-0  rounded-full p-4">
          <FaMapMarkerAlt className="text-[#F56800]" />
        </div>
        <div className="ml-3">
          <h6 className="font-bold text-[#000]">Branch Office</h6>
          <span className="text-[#596277]">Halima Dighir Par,Main Road, Vimpur, Chatkhil, Noakhali.</span>
        </div>
      </div>

      <div className="flex border-b pb-3 mb-3">
        <div className="flex-shrink-0  rounded-full p-4">
          <TbBuildingFactory2  className="text-[#F56800]" />
        </div>
        <div className="ml-3">
          <h6 className="font-bold text-[#000]">Factory</h6>
          <span className="text-[#596277]">Kalidas Gati Bazar, kalidas Gati, Sirajganj.</span>
        </div>
      </div>

     

  
    
      <div className="flex border-b-0 pb-3 mb-3">
        <div className="flex-shrink-0  rounded-full p-4">
          <FaPhoneAlt   className="text-[#F56800]" />
        </div>
        <div className="ml-3">
          <h6 className="font-bold text-[#000]">Phone</h6>
          <span className="text-[#596277]"> 

          Mobile: 01716-537772, 01616537772
          Tel: +88-02-222285360, +88-02-222295013</span>
        </div>
      </div>
      
      <div className="flex border-b-0 pb-3 mb-3">
        <div className="flex-shrink-0  rounded-full p-4">
          <HiOutlineMail    className="text-[#F56800]" />
        </div>
        <div className="ml-3">
          <h6 className="font-bold text-[#000]">Email</h6>
          <span className="text-[#596277]">info.samirtextile@gmail.com</span>
        </div>
      </div>
     

    </div>
    <div className="mt-8 lg:mt-0">
        <h2 className=' text-lg sm:text-3xl font-semibold text-[#000] pb-7'>Need a functional contact form?</h2>
   
    <form>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Input Fields */}
        <div className="form-floating">
          <input
            type="text"
            className="w-full border-2 p-4 border-gray-300 text-[#596277]  placeholder:text-[#596277] outline-none "
            id="name"
            placeholder="Your Name"
          />
         
        </div>
        <div className="form-floating">
          <input
            type="email"
            className="w-full border-2 p-4 border-gray-300 text-[#596277]  placeholder:text-[#596277] outline-none "
            id="email"
            placeholder="Your Email"
          />
       
        </div>
      </div>

      {/* Subject Field */}
      <div className="form-floating mt-4">
        <input
          type="text"
          className="w-full p-4 border-2 border-gray-300 text-[#596277]  placeholder:text-[#596277] outline-none "
          id="subject"
          placeholder="Subject"
        />
    
      </div>

      {/* Message Field */}
      <div className="form-floating mt-4">
        <textarea
          className="w-full p-4  border-2 border-gray-300 text-[#596277]  placeholder:text-[#596277] outline-none "
          id="message"
          placeholder=" Message "
          style={{ height: '100px' }}
        />
       
      </div>

      {/* Submit Button */}
      <button className="w-full uppercase mt-6 bg-[#F56800] text-white  py-3 px-5   transition-colors duration-300">
        Send Message
      </button>
    </form>
  </div>
  </div>

  <iframe
  className="rounded-lg w-full mt-7 h-[250px]"
  src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3650.4959491990436!2d90.42283111540239!3d23.780869793996894!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755c71f636dafaf%3A0xdf280c6d3c2fb65b!2sBadda%20Link%20Road%2C%20Wakil%20Tower!5e0!3m2!1sen!2sbd!4v1696586239836!5m2!1sen!2sbd"
  frameBorder="0"
  allowFullScreen={true}
  aria-hidden="false"
  tabIndex="0"
/>
</div>
</div>


    )
}
export default ContactPage;