
import Link from "next/link";
import { FaChevronRight } from "react-icons/fa6";
import { RxBorderStyle } from "react-icons/rx";
import { FaMapMarkerAlt, FaPhoneAlt, FaEnvelope } from 'react-icons/fa';

export async function generateMetadata() {
    return {
      title: 'Contact Page',
      description: "Generated by create Contact Page",
    }
  }

const ContactPage=()=>{
    return(
<div>
<div className="w-full bg-cover bg-center mb-5" style={{backgroundImage: 'url("/img/bg_parallax3.jpg")'}}>
  <div className="bg-black/70  py-10 sm:py-20">
    <div className="container mx-auto text-center">
      {/* Heading */}
      <h1 className=" text-4xl sm:text-6xl font-semibold text-white mb-3 animate-slide-in-down">
       Contact
      </h1>
      {/* Breadcrumb Navigation */}
      <nav aria-label="breadcrumb">
        <ol className="flex justify-center items-center space-x-3 text-sm uppercase text-white pt-2">
          <li>
            <Link href={"/"} className="text-[#EDDD5E] text-lg">Home </Link>
          </li>
          <li><FaChevronRight /></li>
          <li className="text-white text-lg"> Contact</li>
        </ol>
      </nav>
    </div>
  </div>
</div>
<div className="px-4 sm:px-20 py-10">
<div className="text-center pb-6" style={{ maxWidth: "500px", margin: "0 auto" }}>
      <p className="text-[#5B8C51] flex justify-center text-lg font-semibold uppercase  inline-block py-1 rounded pt-3 sm:pt-0 sm:mb-2 flex items-center">
  <RxBorderStyle className="inline-flex text-2xl font-semibold mr-2" />
   Contact
  <RxBorderStyle className="inline-flex text-2xl font-semibold ml-2" />
</p>

        <h1 className="mb-5 text-3xl lg:text-5xl font-bold text-[#404A3D] text-center">If You Have Any Query, Please Contact </h1>
      </div>
  
  <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mt-8">
    {/* Contact Info Boxes */}
    

    {/* Google Map */}
    <div>
    <div className="flex border-b pb-3 mb-3">
        <div className="flex-shrink-0 bg-[#EDDD5E] rounded-full p-4">
          <FaMapMarkerAlt className="text-gray-600" />
        </div>
        <div className="ml-3">
          <h6 className="font-bold text-[#404A3D]">Our Office</h6>
          <span className="text-[#596277]">1216 Dhaka Bangladesh</span>
        </div>
      </div>

      <div className="flex border-b pb-3 mb-3">
        <div className="flex-shrink-0 bg-[#EDDD5E] rounded-full p-4">
          <FaPhoneAlt className="text-gray-600" />
        </div>
        <div className="ml-3">
          <h6 className="font-bold text-[#404A3D]">Call Us</h6>
          <span className="text-[#596277]">+012 345 67890</span>
        </div>
      </div>

      <div className="flex border-b-0 pb-3 mb-3">
        <div className="flex-shrink-0 bg-[#EDDD5E] rounded-full p-4">
          <FaEnvelope className="text-gray-600" />
        </div>
        <div className="ml-3">
          <h6 className="font-bold text-[#404A3D]">Mail Us</h6>
          <span className="text-[#596277]">info@example.com</span>
        </div>
      </div>
      <iframe
        className="rounded-lg w-full h-[250px]"
        src="https://www.google.com/maps/place/%E0%A6%A2%E0%A6%BE%E0%A6%95%E0%A6%BE/@23.7810672,90.2548725,11z/data=!3m1!4b1!4m6!3m5!1s0x3755b8b087026b81:0x8fa563bbdd5904c2!8m2!3d23.804093!4d90.4152376!16zL20vMGZuYjQ?entry=ttu&g_ep=EgoyMDI0MDkyMy4wIKXMDSoASAFQAw%3D%3D"
        frameBorder="0"
        allowFullScreen
        aria-hidden="false"
        tabIndex="0"
      />
    </div>
    <div className="mt-8 lg:mt-0">
        <h2 className='text-3xl font-semibold text-[#404A3D]'>Need a functional contact form?</h2>
    <p className="mb-4 text-gray-600 text-center lg:text-left py-2">
      The contact form is currently inactive. Get a functional and working contact form with Ajax & PHP in a few minutes. Just copy and paste the files, add a little code and you're done.{' '}
      <a href="https://htmlcodex.com/contact-form" className="text-[#404A3D] font-semibold">Download Now</a>.
    </p>
    <form>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Input Fields */}
        <div className="form-floating">
          <input
            type="text"
            className="w-full border-2 p-4 border-gray-300 text-[#596277]  placeholder:text-[#596277] outline-none "
            id="name"
            placeholder="Your Name"
          />
         
        </div>
        <div className="form-floating">
          <input
            type="email"
            className="w-full border-2 p-4 border-gray-300 text-[#596277]  placeholder:text-[#596277] outline-none "
            id="email"
            placeholder="Your Email"
          />
       
        </div>
      </div>

      {/* Subject Field */}
      <div className="form-floating mt-4">
        <input
          type="text"
          className="w-full p-4 border-2 border-gray-300 text-[#596277]  placeholder:text-[#596277] outline-none "
          id="subject"
          placeholder="Subject"
        />
    
      </div>

      {/* Message Field */}
      <div className="form-floating mt-4">
        <textarea
          className="w-full p-4  border-2 border-gray-300 text-[#596277]  placeholder:text-[#596277] outline-none "
          id="message"
          placeholder=" Message "
          style={{ height: '100px' }}
        />
       
      </div>

      {/* Submit Button */}
      <button className="w-full uppercase mt-6 bg-[#EDDD5E] text-black  py-3 px-5   transition-colors duration-300">
        Send Message
      </button>
    </form>
  </div>
  </div>

 
</div>
</div>


    )
}
export default ContactPage;